name:                core-parser
version:             0.1.0.0
github:              "githubuser/core-parser"
license:             BSD3
author:              "Andrea Biondo"
maintainer:          "andrea.biondo965@gmail.com"
copyright:           "2019 Andrea Biondo"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/abiondo/core-parser#readme>

dependencies:
- base >= 4.7 && < 5
- graphviz
- text
- optparse-declarative

library:
  source-dirs: src

executables:
  core-parser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - core-parser

tests:
  core-parser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - core-parser
    - hspec
